Agio-SES/Agio-SES/Models/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Agio_SES.Models
{
    public class DatabaseContext : DbContext
    {
        public DatabaseContext() : base("DBConnection")
        {

        }
        public DbSet<request_GSPN> request_GSPN { get; set; }

    }
}

Agio-SES/Agio-SES/Models/Request_GSPN.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Agio_SES.Models
{
    [Table("request_GSPN")]
    public class request_GSPN
    {
        [Key]

        public int ID { get; set; }
        public string request_no { get; set; }
        public string ticket { get; set; }
        public Nullable<int> ID_solicitud { get; set; }
        public string localizacion_2 { get; set; }
        public string localizacion_3 { get; set; }
        public string comentarios { get; set; }

    }
}

Agio-SES/Agio-SES/Controllers/AgioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agio_SES.Controllers
{
    public class AgioController : Controller
    {
        // GET: Agio
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CargarInv()
        {
            return View();
        }
        
        public ActionResult Packing()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Inventario()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ConfMaterial()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Inicio()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Reportes()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult CargarGSPN()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

    }
}

Agio-SES/Agio-SES/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agio_SES.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Agio-SES/Agio-SES/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using Agio_SES.Models;

namespace Agio_SES.Controllers
{
    public class RequestController : Controller
    {
        // GET: Request
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ActionResult ShowRequest()
        {
            return View();
        }

        public ActionResult LoadRequest()
        {
            try
            {
                //Creating instance of DatabaseContext class
                using (DatabaseContext _context = new DatabaseContext())
                {
                    var draw = Request.Form.GetValues("draw").FirstOrDefault(); //dibuja secuencia de devoluciones de forma asincrona
                    var start = Request.Form.GetValues("start").FirstOrDefault(); //inicio en el conjunto de datos actual(0 basado en índice, es decir, 0 es el primer registro).
                    var length = Request.Form.GetValues("length").FirstOrDefault();// Número de registros que la tabla puede mostrar
                    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                    var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


                    //Paging Size (10,20,50,100)  
                    int pageSize = length != null ? Convert.ToInt32(length) : 0;
                    int skip = start != null ? Convert.ToInt32(start) : 0;
                    int recordsTotal = 0;

                    // obteniendo todos los datos de la orden 
                    var requestData = (from tempID in _context.request_GSPN
                                     select tempID);

                    //Sorting(clasificación)
                    if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                    {
                        requestData = requestData.OrderBy(sortColumn + " " + sortColumnDir);
                    }

                    ////Search  buscar
                    if (!string.IsNullOrEmpty(searchValue))
                    {
                        requestData = requestData.Where(m => m.request_no == searchValue
                        || m.ticket == searchValue || m.localizacion_2 == searchValue);
                    }

                    //total number of rows count   
                    recordsTotal = requestData.Count();
                    //Paging   
                    var data = requestData.Skip(skip).Take(pageSize).ToList();

                    return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);

                }
            }

            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public ActionResult EditRequest(int? ID)
        {
            try
            {
                using (DatabaseContext _context = new DatabaseContext())
                {
                    var request = (from request_GSPN in _context.request_GSPN
                                 where request_GSPN.ID == ID
                                 select request_GSPN).FirstOrDefault();

                    return View(request);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }


        //[HttpPost]
        //public JsonResult DeleteOrden(string ID)
        //{
        //    using (DatabaseContext _context = new DatabaseContext())
        //    {
        //        var Orden = _context.sc_OrderStatus.Find(ID);

        //        if (ID == null)
        //            return Json(data: "Not Deleted", behavior: JsonRequestBehavior.AllowGet);
        //        _context.sc_OrderStatus.Remove(Orden);
        //        _context.SaveChanges();

        //        return Json(data: "Deleted", behavior: JsonRequestBehavior.AllowGet);
        //    }
        //}

    }
}

Agio-SES/Agio-SES/Views/Agio/CargarGSPN.cshtml
@{
    ViewBag.Title = "CargarGSPN";
}

<link rel=StyleSheet type="text/css" href="~/Content/css/CargarGSPN.css"> <!--Aqui esta mi hoja de estilo-->


<!doctype html>
<html lang="en">
<head>
    <h1 class="display-1">Ingreso a GSPN</h1>
</head>
<header>
   
</header>

<body>


   

    <div class="card">
        <div class="card-header"> <h2> Sube tus archivos GSPN </h2> </div>
        <div class="card-body">
            <!-- contenido del CARD -->
            <div class="modal-body">
                <div class="row mx-auto">
                    <div class="col-md-10">
                        <div class="custom-file mb-3">
                            <input type="file" class="custom-file-input" id="customFile" name="filename">
                            <label class="custom-file-label" for="customFile">Subir Archivo...</label>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button class="btn-block btn btn-outline-success"><b>Subir</b></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">Gracias</div>
    </div>
    <br />
</body>
</html>

Agio-SES/Agio-SES/Views/Agio/CargarInv.cshtml
@{
    ViewBag.Title = "CargarInv";
}
<link rel=StyleSheet type="text/css" href="~/Content/css/CargarInv.css"> 


<br />
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <h1 class="display-1">Ingreso a inventario</h1>
</head>
<body>
    <header>
        
    </header>
    <!--Aqui empieza CARD-->
    <div class="container">
        <div class="card">
            <div class="card-header"><h2>Sube tu archivo que deseas agregar a inventario</h2></div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="custom-file mb-3">
                            <input type="file" class="custom-file-input" id="customFile" name="filename">
                            <label class="custom-file-label" for="customFile">Subir Archivo...</label>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <button class="btn-block btn btn-outline-success"><b>Subir</b></button>
                    </div>
                </div>


            </div>
            <div class="card-footer">Gracias</div>
        </div>
    </div>


    
    
</body>
</html>

Agio-SES/Agio-SES/Views/Agio/ConfMaterial.cshtml
@{
    ViewBag.Title = "ConfMaterial";
}
@*<link rel=StyleSheet type="text/css" href="~/Content/css/diseño.css">*@ <!--Aqui esta mi hoja de estilo-->


<!DOCTYPE html>
<html lang="en">

<body>
    <header>
    </header>
    <br />
    <br>
    <div class="container" style="background-color: white; padding-bottom: 20px ">
        <div class="row" style="padding-top: 20px">
            <div class="col-md-12">
                <h2 class="text-center text-secondary"><b>Material Entregado</b></h2><hr>
            </div>
        </div>
        <div class="row">
            <div class="col md 2">
                <select name="" id="" class="form-control">
                    <option value="">P030320-01</option>
                    <option value="">P030320-02</option>
                    <option value="">P030320-03</option>
                    <option value="">P030320-04</option>
                    <option value="">P030320-05</option>
                    <option value="">P030320-06</option>
                    <option value="">P030320-07</option>
                    <option value="">P040320-01</option>
                    <option value="">P050320-02</option>
                    <option value="">P060320-03</option>
                    <option value="">P070320-04</option>
                    <option value="">P080320-05</option>
                    <option value="">P090320-06</option>
                </select>
            </div>
            <div class="col md 8"></div>
            <div class="col md 2">
                <input type="text" placeholder="Buscar..." class="form-control">
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col md 12">
                <table class="table table-hover table-responsive text-center">
                    <thead style="background-color: #008E99" class="text-light">
                        <tr>
                            <th>#</th>
                            <th>No. Packing</th>
                            <th>No. Parte</th>
                            <th>Ingeniero</th>
                            <th>Solicitud de Parte</th>
                            <th>No. Orden</th>
                            <th>Folio ASC</th>
                            <th>Delivery</th>
                            <th>Fecha</th>
                            <th>Hora Firma</th>
                            <th>ID_AGI</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>P130320-02</td>
                            <td>SVC COVER ASSY-B/G;LATIN_ZB_A205_VN;SM-A</td>
                            <td>JUAN ANTONIO GARCIA RIOS</td>
                            <td>GH82-19641A</td>
                            <td>4154258745</td>
                            <td>M511032000071</td>
                            <td>8509767772000420</td>
                            <td>03/03/2020</td>
                            <td>16:30</td>
                            <td>RQUESTED</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>P130320-02</td>
                            <td>SVC COVER ASSY-B/G;LATIN_ZB_A205_VN;SM-A</td>
                            <td>JUAN ANTONIO GARCIA RIOS</td>
                            <td>GH82-19641A</td>
                            <td>4154258745</td>
                            <td>M511032000071</td>
                            <td>8509767772000420</td>
                            <td>03/03/2020</td>
                            <td>16:30</td>
                            <td>RQUESTED</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>P130320-03</td>
                            <td>SVC COVER ASSY-B/G;LATIN_ZB_A205_VN;SM-A</td>
                            <td>JUAN ANTONIO GARCIA RIOS</td>
                            <td>GH82-19641A</td>
                            <td>4154258745</td>
                            <td>M511032000071</td>
                            <td>8509767772000420</td>
                            <td>03/03/2020</td>
                            <td>16:30</td>
                            <td>RQUESTED</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>P130320-03</td>
                            <td>SVC COVER ASSY-B/G;LATIN_ZB_A205_VN;SM-A</td>
                            <td>JUAN ANTONIO GARCIA RIOS</td>
                            <td>GH82-19641A</td>
                            <td>4154258745</td>
                            <td>M511032000071</td>
                            <td>8509767772000420</td>
                            <td>03/03/2020</td>
                            <td>16:30</td>
                            <td>RQUESTED</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>
</html>

Agio-SES/Agio-SES/Views/Agio/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel=StyleSheet type="text/css" href="~/Content/css/diseño.css"> <!--Aqui esta mi hoja de estilo-->


<title>@ViewBag.Title - Mi aplicación ASP.NET</title>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")

<html>
<body>

   

        <div class="jumbotron">
            <div class="container">
                <br />
                <h1 class="display-1">Almacen GSPN</h1>
                <p>
                    Sube tus archivos GSPN, controla los flujos de entradas y salidas de tu inventario y gestióna el (control de entrga de material al tecnico etc... )
                    Estos flujos suelen no estar coordinados y esa es una de las razones por las que se precisa definir una óptima logística de almacenamiento.
                </p>

            </div>
        </div>



</body>
</html>

Agio-SES/Agio-SES/Views/Agio/Reportes.cshtml
@{
    ViewBag.Title = "Reportes";
}
@*<link rel=StyleSheet type="text/css" href="~/Content/css/diseño.css">*@ <!--Aqui esta mi hoja de estilo-->

Agio-SES/Agio-SES/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Agio-SES/Agio-SES/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Agio-SES/Agio-SES/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link rel=StyleSheet type="text/css" href="~/Content/css/Index.css"> @*Aqui esta mi hoja de estilo*@


<div>
    <div class="container">
        <h1>Almacen GSPN</h1>
        <p class="text-center">
            Sube tus archivos GSPN, controla los flujos de entradas y salidas de tu inventario y gestióna el (control de entrga de material al tecnico etc... )
            Estos flujos suelen no estar coordinados y esa es una de las razones por las que se precisa definir una óptima logística de almacenamiento.
        </p>

    </div>
</div>

Agio-SES/Agio-SES/Views/Request/EditRequest.cshtml
@model Agio_SES.Models.request_GSPN
@{
    ViewBag.Title = "EditRequest";
}

<h2>EditRequest</h2>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4> Request </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.request_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.request_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.request_no, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ticket, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ticket, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ticket, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ID_solicitud, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ID_solicitud, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_solicitud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localizacion_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.localizacion_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localizacion_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localizacion_3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.localizacion_3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localizacion_3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comentarios, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.comentarios, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comentarios, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "ShowRequest", "Request")
    </div>
</body>
</html>

Agio-SES/Agio-SES/Views/Request/ShowRequest.cshtml
@{
    ViewBag.Title = "ShowRequest";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>





    <script>
        $(document).ready(function () {
            $("#demoRequest").DataTable({

                "processing": true, // muestra el mensaje de procesando
                "serverSide": true, // calculos del procesamiento (filtrado, paginación y clasificación)
                "filter": true, // habilita el cuadro de busqueda (search box)
                "orderMulti": false, // for disable multiple column at once ordena multiples columnas
                "pageLength": 10,

                "ajax": {
                    "url": "/Request/LoadRequest",
                    "type": "POST",
                    "datatype": "json"
                },

                "columnDefs":
                    [{
                        "targets": [0],
                        "visible": true,
                        "searchable": true
                    },
                    {
                        "targets": [1],
                        "visible": true,
                        "searchable": true
                    },
                    {
                        "targets": [2],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [3],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [4],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [5],
                        "searchable": false,
                        "orderable": false
                    }

                    ],

                "columns": [
                    { "data": "ID", "name": "ID", "autoWidth": true },
                    { "data": "request_no", "name": "request_no", "autoWidth": true },
                    { "data": "ticket", "name": "ticket", "autoWidth": true },
                    { "data": "ID_solicitud", "name": "ID_solicitud", "autoWidth": true },
                    { "data": "localizacion_2", "name": "localizacion_2", "autoWidth": true },
                    { "data": "localizacion_3", "name": "localizacion_3", "autoWidth": true },
                    { "data": "comentarios", "name": "comentarios", "autoWidth": true },
                
                 {
                    "render": function (data, type, full, meta) {
                        return '<a class="btn btn-info" href="/Request/EditRequest/' + full.ID + '">Edit</a>';
                    }
                 }

                ]
            });
        });
    </script>

    @*<script>

            function DeleteData(OrderID) {
                if (confirm("Are you sure you want to delete ...?")) {
                    Delete(OrderID);
                }
                else {
                    return false;
                }
            }


            function Delete(OrderID) {
                var url = '@Url.Content("~/")' + "OrderStatus/DeleteOrder";
                $.post(url, { ID: OrderID }, function (data) {
                    if (data == "Deleted") {
                        alert("Delete Order !");
                        oTable = $('#demoOrder').DataTable();
                        oTable.draw();
                    }
                    else {
                        alert("Something Went Wrong!");
                    }
                });
            }
        </script>*@

</head>
<body>
    <div class="container">
        <br />
        @*<div style="width:100%; margin:0 auto;">*@
        <table id="demoRequest" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>request_no</th>
                    <th>ticket</th>
                    <th>ID_solicitud</th>
                    <th>localizacion_2</th>
                    <th>localizacion_3</th>
                    <th>comentarios</th>
                    <th>Edit</th>
                    @*<th>Delete</th>*@
                </tr>
            </thead>
        </table>
    </div>
    @*</div>*@
</body>
</html>

Agio-SES/Agio-SES/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel=StyleSheet type="text/css" href="~/Content/css/diseño.css"> @*Aqui esta mi hoja de estilo*@
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" href="#"></a>
        <a href="~/"> <img src="~/Content/img/logo-blanco.png" alt="logo" style="width:100px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @*@Html.ActionLink("Agiotech", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Archivos</a>
                    <div class="dropdown-menu" aria-label="dropdown01">
                        <a class="dropdown-item" href="#"> @Html.ActionLink("Archivo GSPN", "CargarGSPN", "Agio")</a>
                        <a class="dropdown-item" href="#"> @Html.ActionLink("Archivo Inventario", "CargarInv", "Agio")</a>
                    </div>
                </li>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @*<li>@Html.ActionLink("Index", "Index", "Agio")</li>*@
                        <li>@Html.ActionLink("Packing", "Packing", "Agio")</li>
                        <li>@Html.ActionLink("Material Confirmado", "ConfMaterial", "Agio")</li>
                        <li>@Html.ActionLink("Inventario", "Inventario", "Agio")</li>
                        <li>@Html.ActionLink("Request GSPN", "showRequest", "Request")</li>
                        <li>@Html.ActionLink("Reportes", "Reportes", "Agio")</li>
                    </ul>
                </div>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Packing" aria-label="search">
                <button class="btn btn-secondary" type="submit">Buscar</button>
            </form>
        </div>
    </nav>

    <!--Aquí empieza mi menú vertical-->

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <button class="dropdown-btn">Archivos
    <i class="fa fa-caret-down"></i>
  </button>
        <div class="dropdown-container">
            <a href="#">@Html.ActionLink("Archivo GSPN", "CargarGSPN", "Agio")</a>
            <a href="#"> @Html.ActionLink("Archivo Inventario", "CargarInv", "Agio")</a>
          
        </div>
        <div>
            <a href="#">@Html.ActionLink("Packing", "Packing", "Agio")</a>
            <a href="#">@Html.ActionLink("Material Confirmado", "ConfMaterial", "Agio")</a>
            <a href="#">@Html.ActionLink("Inventario", "Inventario", "Agio")</a>
            <a href="#">@Html.ActionLink("Request GSPN", "showRequest", "Request")</a>
            <a href="#">@Html.ActionLink("Reportes", "Reportes", "Agio")</a>
        </div>
        <a href="#contact">Search</a>
    </div>

    <div id="main">

        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Almacen</span>
    </div>



    <div class="container  ">
        @RenderBody()
    </div>
    
    @*COMENTE--> estos 3 scrips de abajo por que generaba conflicto con DataTable no muestra las propiedades- By Gabriela Blas*@

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)*@

    <script>
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "1";
            document.getElementById("main").style.marginLeft = "1";
        }
    </script>

    <!--Este es es ek scrip del dropdown-->

    <script>
        /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>
</body>
</html>